version: '3'

services:
    neo:
        image: neo4j:4.0.2
        environment:
            - NEO4J_AUTH=neo4j/ub1JOnQcuV^rfBsr5%Ek
        volumes:
            - ./data/neo4j:/data

    rds:
        image: redis:5.0.7

    broadcast:
        network_mode: host
        build:
            context: broadcast
            dockerfile: dockerfile
        environment:
            - HOST=192.168.199.133
            - PORT=80

    web:
        build:
            context: .
            dockerfile: web/dockerfile
        environment:
            - REDIS_HOST=rds
            - NEO_HOST=neo
            - NEO_USER=neo4j
            - NEO_PASSWD=ub1JOnQcuV^rfBsr5%Ek
            - GPG_HOME=/gpg
            - ADMIN_FINGERPRINT=F3215C06348E28B6455F2AEDEDCF1044A9C06456
        ports:
            - 80:80
        volumes:
            - ./data/gpg:/gpg
        depends_on:
            - neo
            - rds

